from PyQt6 import QtCore, QtGui, QtWidgets
from direction_calculator import DirectionCalculator
from matplotlib.backends.backend_qtagg import FigureCanvas
from matplotlib.backends.backend_qtagg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.backends.qt_compat import QtWidgets
from matplotlib.figure import Figure
from my_math import ApproxMode, FilterAlgo

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 706)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.main_tabWidget.setObjectName("main_tabWidget")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.phi_pel_label = QtWidgets.QLabel(parent=self.main_tab)
        self.phi_pel_label.setObjectName("phi_pel_label")
        self.verticalLayout_4.addWidget(self.phi_pel_label)
        self.phi_pel_spinBox = QtWidgets.QDoubleSpinBox(parent=self.main_tab)
        self.phi_pel_spinBox.setObjectName("phi_pel_spinBox")
        self.phi_pel_spinBox.setMinimum(-45)
        self.phi_pel_spinBox.setMaximum(45)
        self.verticalLayout_4.addWidget(self.phi_pel_spinBox)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label1 = QtWidgets.QLabel(parent=self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setMinimumSize(QtCore.QSize(0, 0))
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.main_tab)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.res_label = QtWidgets.QLabel(parent=self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.res_label.sizePolicy().hasHeightForWidth())
        self.res_label.setSizePolicy(sizePolicy)
        self.res_label.setText("")
        self.res_label.setScaledContents(False)
        self.res_label.setObjectName("res_label")
        self.gridLayout.addWidget(self.res_label, 0, 1, 1, 1)
        self.accuracy_label = QtWidgets.QLabel(parent=self.main_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accuracy_label.sizePolicy().hasHeightForWidth())
        self.accuracy_label.setSizePolicy(sizePolicy)
        self.accuracy_label.setText("")
        self.accuracy_label.setScaledContents(False)
        self.accuracy_label.setObjectName("accuracy_label")
        self.gridLayout.addWidget(self.accuracy_label, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.submit_button = QtWidgets.QPushButton(parent=self.main_tab)
        self.submit_button.setObjectName("submit_button")
        self.horizontalLayout.addWidget(self.submit_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.main_tab)
        self.tabWidget.setObjectName("tabWidget")
        self.adfr_tab = QtWidgets.QWidget()
        self.adfr_tab.setObjectName("adfr_tab")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.adfr_tab)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWidget.addTab(self.adfr_tab, "")
        self.e_tab = QtWidgets.QWidget()
        self.e_tab.setObjectName("e_tab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.e_tab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tabWidget.addTab(self.e_tab, "")
        self.amp_tab = QtWidgets.QWidget()
        self.amp_tab.setObjectName("amp_tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.amp_tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tabWidget.addTab(self.amp_tab, "")
        self.phase_tab = QtWidgets.QWidget()
        self.phase_tab.setObjectName("phase_tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.phase_tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget.addTab(self.phase_tab, "")
        self.ampphase_tab = QtWidgets.QWidget()
        self.ampphase_tab.setObjectName("ampphase_tab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ampphase_tab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget.addTab(self.ampphase_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.main_tabWidget.addTab(self.main_tab, "")
        self.settings_tab = QtWidgets.QWidget()
        self.settings_tab.setObjectName("settings_tab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.settings_tab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.phi_0_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.phi_0_label.setObjectName("phi_0_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.phi_0_label)
        self.phi_0_spinBox = QtWidgets.QDoubleSpinBox(parent=self.settings_tab)
        self.phi_0_spinBox.setMinimum(-180.0)
        self.phi_0_spinBox.setMaximum(180.0)
        self.phi_0_spinBox.setSingleStep(0.1)
        self.phi_0_spinBox.setProperty("value", 6.0)
        self.phi_0_spinBox.setObjectName("phi_0_spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phi_0_spinBox)
        self.phi_n_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.phi_n_label.setObjectName("phi_n_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.phi_n_label)
        self.phi_n_spinBox = QtWidgets.QDoubleSpinBox(parent=self.settings_tab)
        self.phi_n_spinBox.setMaximum(180.0)
        self.phi_n_spinBox.setSingleStep(0.1)
        self.phi_n_spinBox.setProperty("value", 0.05)
        self.phi_n_spinBox.setObjectName("phi_n_spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phi_n_spinBox)
        self.k_n_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.k_n_label.setObjectName("k_n_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.k_n_label)
        self.k_n_spinBox = QtWidgets.QDoubleSpinBox(parent=self.settings_tab)
        self.k_n_spinBox.setMinimum(0.8)
        self.k_n_spinBox.setMaximum(1.0)
        self.k_n_spinBox.setSingleStep(0.1)
        self.k_n_spinBox.setProperty("value", 0.9)
        self.k_n_spinBox.setObjectName("k_n_spinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.k_n_spinBox)
        self.angle_range_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.angle_range_label.setObjectName("angle_range_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.angle_range_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.from_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.from_label.setObjectName("from_label")
        self.horizontalLayout_3.addWidget(self.from_label)
        self.phi_min_spinBox = QtWidgets.QDoubleSpinBox(parent=self.settings_tab)
        self.phi_min_spinBox.setMinimum(-180.0)
        self.phi_min_spinBox.setMaximum(180.0)
        self.phi_min_spinBox.setProperty("value", -35.0)
        self.phi_min_spinBox.setObjectName("phi_min_spinBox")
        self.horizontalLayout_3.addWidget(self.phi_min_spinBox)
        self.to_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.to_label.setObjectName("to_label")
        self.horizontalLayout_3.addWidget(self.to_label)
        self.phi_max_spinBox = QtWidgets.QDoubleSpinBox(parent=self.settings_tab)
        self.phi_max_spinBox.setMinimum(-180.0)
        self.phi_max_spinBox.setMaximum(180.0)
        self.phi_max_spinBox.setProperty("value", 35.0)
        self.phi_max_spinBox.setObjectName("phi_max_spinBox")
        self.horizontalLayout_3.addWidget(self.phi_max_spinBox)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_3)
        self.f_c_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.f_c_label.setObjectName("f_c_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.f_c_label)
        self.f_c_spinBox = QtWidgets.QDoubleSpinBox(parent=self.settings_tab)
        self.f_c_spinBox.setMaximum(1000.0)
        self.f_c_spinBox.setSingleStep(0.1)
        self.f_c_spinBox.setProperty("value", 3.0)
        self.f_c_spinBox.setObjectName("f_c_spinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.f_c_spinBox)
        self.filter_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.filter_label.setObjectName("filter_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.filter_label)
        self.filter_checkBox = QtWidgets.QCheckBox(parent=self.settings_tab)
        self.filter_checkBox.setObjectName("filter_checkBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.filter_checkBox)
        self.filter_algo_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.filter_algo_label.setObjectName("filter_algo_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.filter_algo_label)
        self.filter_algo_comboBox = QtWidgets.QComboBox(parent=self.settings_tab)
        self.filter_algo_comboBox.setObjectName("filter_algo_comboBox")
        self.filter_algo_comboBox.addItem("")
        self.filter_algo_comboBox.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.filter_algo_comboBox)
        self.approx_mode_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.approx_mode_label.setObjectName("approx_mode_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.approx_mode_label)
        self.approx_mode_combo_box = QtWidgets.QComboBox(parent=self.settings_tab)
        self.approx_mode_combo_box.setMinimumSize(QtCore.QSize(200, 0))
        self.approx_mode_combo_box.setObjectName("approx_mode_combo_box")
        self.approx_mode_combo_box.addItem("")
        self.approx_mode_combo_box.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.approx_mode_combo_box)
        self.poly_degree_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.poly_degree_label.setObjectName("poly_degree_label")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.poly_degree_label)
        self.poly_degree_spinBox = QtWidgets.QSpinBox(parent=self.settings_tab)
        self.poly_degree_spinBox.setMaximum(50)
        self.poly_degree_spinBox.setProperty("value", 10)
        self.poly_degree_spinBox.setObjectName("poly_degree_spinBox")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.FieldRole, self.poly_degree_spinBox)
        self.noise_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.noise_label.setObjectName("noise_label")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.noise_label)
        self.noise_checkBox = QtWidgets.QCheckBox(parent=self.settings_tab)
        self.noise_checkBox.setObjectName("noise_checkBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.FieldRole, self.noise_checkBox)
        self.q_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.q_label.setObjectName("q_label")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.LabelRole, self.q_label)
        self.q_spinBox = QtWidgets.QSpinBox(parent=self.settings_tab)
        self.q_spinBox.setProperty("value", 14)
        self.q_spinBox.setObjectName("q_spinBox")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.ItemRole.FieldRole, self.q_spinBox)
        self.horizontalLayout_9.addLayout(self.formLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.paths_label = QtWidgets.QLabel(parent=self.settings_tab)
        font = QtGui.QFont()
        font.setBold(True)
        self.paths_label.setFont(font)
        self.paths_label.setObjectName("paths_label")
        self.verticalLayout_5.addWidget(self.paths_label)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.sll1_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.sll1_label.setObjectName("sll1_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sll1_label)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sll1_lineEdit = QtWidgets.QLineEdit(parent=self.settings_tab)
        self.sll1_lineEdit.setObjectName("sll1_lineEdit")
        self.horizontalLayout_4.addWidget(self.sll1_lineEdit)
        self.sll1_button = QtWidgets.QToolButton(parent=self.settings_tab)
        self.sll1_button.setObjectName("sll1_button")
        self.horizontalLayout_4.addWidget(self.sll1_button)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_4)
        self.sll2_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.sll2_label.setObjectName("sll2_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sll2_label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.sll2_lineEdit = QtWidgets.QLineEdit(parent=self.settings_tab)
        self.sll2_lineEdit.setObjectName("sll2_lineEdit")
        self.horizontalLayout_5.addWidget(self.sll2_lineEdit)
        self.sll2_button = QtWidgets.QToolButton(parent=self.settings_tab)
        self.sll2_button.setObjectName("sll2_button")
        self.horizontalLayout_5.addWidget(self.sll2_button)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_5)
        self.faz_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.faz_label.setObjectName("faz_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.faz_label)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.faz_lineEdit = QtWidgets.QLineEdit(parent=self.settings_tab)
        self.faz_lineEdit.setObjectName("faz_lineEdit")
        self.horizontalLayout_6.addWidget(self.faz_lineEdit)
        self.faz_button = QtWidgets.QToolButton(parent=self.settings_tab)
        self.faz_button.setObjectName("faz_button")
        self.horizontalLayout_6.addWidget(self.faz_button)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_6)
        self.freq_num_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.freq_num_label.setObjectName("freq_num_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.freq_num_label)
        self.freq_num_spinBox = QtWidgets.QSpinBox(parent=self.settings_tab)
        self.freq_num_spinBox.setMaximum(17)
        self.freq_num_spinBox.setProperty("value", 6)
        self.freq_num_spinBox.setObjectName("freq_num_spinBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.freq_num_spinBox)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.t_arr_label = QtWidgets.QLabel(parent=self.settings_tab)
        font = QtGui.QFont()
        font.setBold(True)
        self.t_arr_label.setFont(font)
        self.t_arr_label.setObjectName("t_arr_label")
        self.verticalLayout_5.addWidget(self.t_arr_label)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.t_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.t_label.setObjectName("t_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.t_label)
        self.t_spinBox = QtWidgets.QDoubleSpinBox(parent=self.settings_tab)
        self.t_spinBox.setProperty("value", 2)
        self.t_spinBox.setObjectName("t_spinBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.t_spinBox)
        self.f_discr_label = QtWidgets.QLabel(parent=self.settings_tab)
        self.f_discr_label.setObjectName("f_discr_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.f_discr_label)
        self.f_discr_spinBox = QtWidgets.QDoubleSpinBox(parent=self.settings_tab)
        self.f_discr_spinBox.setProperty("value", 50)
        self.f_discr_spinBox.setObjectName("f_discr_spinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.f_discr_spinBox)
        self.verticalLayout_5.addLayout(self.formLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.main_tabWidget.addTab(self.settings_tab, "")
        self.verticalLayout_2.addWidget(self.main_tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Пеленгатор"))
        self.phi_pel_label.setText(_translate("MainWindow", "Заданный угол, [град]:"))
        self.label1.setText(_translate("MainWindow", "Вычисленный угол: "))
        self.label_3.setText(_translate("MainWindow", "Погрешность:"))
        self.submit_button.setText(_translate("MainWindow", "Расчет"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.adfr_tab), _translate("MainWindow", "АПХ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.e_tab), _translate("MainWindow", "E"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.amp_tab), _translate("MainWindow", "Амплитудный метод"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.phase_tab), _translate("MainWindow", "Фазовый метод"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ampphase_tab), _translate("MainWindow", "Амплитудно-фазовый метод"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.main_tab), _translate("MainWindow", "Расчет"))
        self.phi_0_label.setText(_translate("MainWindow", "φ0, [град]"))
        self.phi_n_label.setText(_translate("MainWindow", "φн"))
        self.k_n_label.setText(_translate("MainWindow", "Kн"))
        self.angle_range_label.setText(_translate("MainWindow", "Диапазон углов, [град]"))
        self.from_label.setText(_translate("MainWindow", "От"))
        self.to_label.setText(_translate("MainWindow", "До"))
        self.f_c_label.setText(_translate("MainWindow", "fc, ГГц"))
        self.filter_label.setText(_translate("MainWindow", "Фильтрация"))
        self.filter_checkBox.setText(_translate("MainWindow", "Вкл"))
        self.filter_algo_label.setText(_translate("MainWindow", "Алгоритм фильтрации"))
        self.filter_algo_comboBox.setItemText(0, _translate("MainWindow", "Савитский-Голей"))
        self.filter_algo_comboBox.setItemText(1, _translate("MainWindow", "Баттеруорта"))
        self.approx_mode_label.setText(_translate("MainWindow", "Алгоритм аппроксимации"))
        self.approx_mode_combo_box.setItemText(0, _translate("MainWindow", "Аппроксимация полиномом"))
        self.approx_mode_combo_box.setItemText(1, _translate("MainWindow", "Линейная аппроксимация"))
        self.poly_degree_label.setText(_translate("MainWindow", "Степень полинома"))
        self.noise_label.setText(_translate("MainWindow", "Шум"))
        self.noise_checkBox.setText(_translate("MainWindow", "Вкл"))
        self.q_label.setText(_translate("MainWindow", "Сигнал/Шум, [дБ]"))
        self.paths_label.setText(_translate("MainWindow", "Пути к файлам:"))
        self.sll1_label.setText(_translate("MainWindow", "ДНА первой антенны"))
        self.sll1_lineEdit.setText(_translate("MainWindow", "pel_data/12.txt"))
        self.sll1_button.setText(_translate("MainWindow", "..."))
        self.sll2_label.setText(_translate("MainWindow", "ДНА второй антенны"))
        self.sll2_lineEdit.setText(_translate("MainWindow", "pel_data/13.txt"))
        self.sll2_button.setText(_translate("MainWindow", "..."))
        self.faz_label.setText(_translate("MainWindow", "ФПХ"))
        self.faz_lineEdit.setText(_translate("MainWindow", "pel_data/faz.txt"))
        self.faz_button.setText(_translate("MainWindow", "..."))
        self.freq_num_label.setText(_translate("MainWindow", "Номер частоты"))
        self.t_arr_label.setText(_translate("MainWindow", "Настройки моделирования"))
        self.t_label.setText(_translate("MainWindow", "Время моделирования, [нс]"))
        self.f_discr_label.setText(_translate("MainWindow", "Частота дискретизации, [ГГц]"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.settings_tab), _translate("MainWindow", "Параметры"))
        
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
